schemaspy.t=pgsql11
schemaspy.dp=/drivers
schemaspy.host=db
schemaspy.port=5432
schemaspy.db=app_db
schemaspy.s=public
schemaspy.u=postgres
schemaspy.p=password
schemaspy.o=/output
schemaspy.vizjs=true
schemaspy.norows=true